config/routes.rb
Rails.application.routes.draw do
  resources :responses

  resources :articles

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many  :responses, dependent: :destroy
	validates :content, :name, :title, :presence => true
end

app/models/response.rb
class Response < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @response = Response.new    
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @response = Response.new 
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :name, :content)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to root_path, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:name, :content, :article_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id='focusposition'></div>
<div id='realtime' ></div><br>
  <div class="field">
    <%= f.text_field :title ,placeholder: "タイトル..."%>
  </div>
  <div class="field">
    <%= f.text_field :name ,placeholder: "名前..."%>
  </div>
  <div class="field">
    <%= f.text_area :content ,:size=>"60x10",:oninput=>'PreView2()',placeholder: "内容..."%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>$\mathcal{ \color{red}{Math.B.B.S.}}$</h1>
<h1>$\tiny{ Mathematical\ Bulletin\ Board\ System}$</h1>

<% @articles.each do |article| %>
  <h2><%= article.title %></h2>
  <strong>
    <p>
      <%= article.name %>
      <%= article.updated_at.strftime "%Y年%m月%d日 %H時%M分" %>
    </p>
    <div1><%= article.content %></div1>
  </strong>
  <% article.responses.each do |response| %>
      <p>
        <%= response.name %> : 
        <%= response.updated_at.strftime "%Y年%m月%d日 %H時%M分" %>
      </p>
      <div1><%= response.content %></div1>  
  <% end %>

    <br><br><br><br><br>
    <br><br><br><br><br>
    <br><br><br><br><br>
    <br><br><br><br><br>
  <%= form_for(@response) do |f| %>
    <% if @response.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

        <ul>
        <% @response.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <span id='realtime' ></span>
    <div class="sets">
      <div class="field">
        <%= f.text_field :name ,placeholder: "名前"%>
        <span3 class="actions">
          <%= f.submit :value =>"送信" %>
          <div >
            <%= f.text_area :content ,:size=>"30x4",:oninput=>'PreView1()',placeholder: "内容..."%>  
          </div>
          <div >
            <%= f.hidden_field :article_id, :value => article.id %>
          </div>
        </span3>
      </div>
    </div>
  <% end %>
<% end %>
<div id='focusposition'>　</div>

app/views/articles/new.html.erb
<h1>新規作成</h1>

<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<% @article.responses.each do |response| %>
      <p>
        <%= response.name %>
      </p>
      <p>
        <%= response.content %>
        <%= link_to 'Destroy', response_path(response), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>

<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content ,:size=>"60x10"%>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Math.B.B.S.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="/favicon.ico" type="image/vnd.microsoft.icon">
  <meta name="keywords" content="数学掲示板,数学,掲示板,数式,MathJax,javascript">
  <meta name="description" content="綺麗な数式を簡単に表示できる掲示板です。MathJaxやjavascriptを応用し、紙に書くのと変わらない書き心地を目指しています。">
  <script type="text/x-mathjax-config">MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ["\\(","\\)"]] } });</script>
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
  <meta http-equiv="X-UA-Compatible" CONTENT="IE=EmulateIE7" />
  <script>
  document.addEventListener('DOMContentLoaded',function(){ document.getElementById('focusposition').focus();},false);


  function MathChange(output){
      output = output.replace(/\{/g,'\\left\\{\\right.');
      output = output.replace(/\}/g,'\\left.\\right\\}');
      output = output.replace(/\^\\left\\{\\right.(.*?)\\left.\\right\\}/g,'^{$1}');
      output = output.replace(/\_\\left\\{\\right.(.*?)\\left.\\right\\}/g,'_{$1}');
      output = output.replace(/\r\n/g,'\n');
      output = output.replace(/\r/g,'\n');
      output = output.replace(/\n/g,'\\\\ ');//改行
      output = output.replace(/\s /g,'\\ ');//スペース登録

     
    var fullWidth = 'ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ０１２３４５６７８９、。＾＋－（）｛｝'; 
    var halfWidth = 'abcdefghijklmnopqrstuvwxyz0123456789,.^+-(){}'; 
    for (var i=0,I=fullWidth.length; i<I; i++)
      output = output.replace(new RegExp(fullWidth.charAt(i),'g'),halfWidth.charAt(i));

    function divide(original){
      var slash = [], par = 0;
      for (var i=0,I=original.length; i<I; i++){
        var character = original.charAt(i);//i番目の配列を抜き出す
        switch (character){//以下でslash配列に/ごとの()の数を記憶させる
          case '(': par++; break;//character=='('ならpar=par+1
          case ')': par--; break;//character==')'ならpar=par+1
          case '/': slash.push([par,i]); break;//slash配列に[par,i]を記憶させてbreak
        }
      }
      var S = slash.length;//分数の分割の数
      if (S>0){//分数があれば
        for (var i=1,min=slash[0][0]; i<S; i++) min = Math.min(slash[i][0],min);//配列slashi番目のparの最小をminとする
        for (var i=0,minSlash=[-1]; i<S; i++) if (slash[i][0]==min) minSlash.push(slash[i][1]);//もしparが最小なら　その値をminSlashに入れる
        minSlash.push(I);//
        var parts = [];
        for (var i=0,M=minSlash.length; i<M-1; i++){
          parts[i] = original.slice(minSlash[i]+1,minSlash[i+1]);
          if (parts[i].indexOf('/')>=0) parts[i] = divide(parts[i]);
        }
        for (var i=0,I=parts.length-1; i<I; i++){
          for (var j=parts[i].length-1,par=0; j>=0; j--){
            var character = parts[i].charAt(j);
            if (character==')') par++;
            if (character=='(') par--;
            var flag = character.match(/[^A-Za-z0-9\*×\(\)]/);
            var flag2 = character.match(/[^A-Za-z0-9\*×]/);
            if ((par==0 && (flag || j==0)) || (par==-1 && flag2)){
              if (par==0 && !flag && j==0) j--;
              parts[i] = (parts[i].charAt(j+1)==('(') && parts[i].charAt(parts[i].length-1)==(')') && parts[i].slice(j+1).indexOf(')(')<0) ? parts[i].slice(0,j+1)+parts[i].slice(j+1).replace(/\((.*)\)/,'\\dfrac {$1}') : parts[i].slice(0,j+1)+'\\dfrac {'+parts[i].slice(j+1)+'}';
              break;
            }
          }
          for (var j=0,J=parts[i+1].length,par=0; j<J; j++){
            var character = parts[i+1].charAt(j);
            if (character=='(') par++;
            if (character==')') par--;
            var flag = character.match(/[^A-Za-z0-9\*×\(\)]/);
            if ((par==0 && (flag || j==J-1)) || (par==-1 && flag2)){
              if (par==0 && !flag && j==J-1) j++;
                parts[i+1] = (parts[i+1].charAt(0)==('(') && parts[i+1].charAt(j-1)==(')') && parts[i+1].slice(0,j).indexOf(')(')<0) ? parts[i+1].slice(0,j).replace(/\((.*)\)/,'{$1}')+parts[i+1].slice(j) : '{'+parts[i+1].slice(0,j)+'}'+parts[i+1].slice(j);
              break;
            }
          }
        }

        parts = parts.join('');

      }
      else var parts = original;
      return parts;
    }
    output = divide(output);//分数にする

   
    output = output.replace(/積分\(\)/g,'\\displaystyle\\int\\ \\!\\ \\!\\ \\! ');
    output = output.replace(/積分\((.*?)(から|,)(.*?)\)/g,'\\displaystyle\\int_{$1}^{$3}\ \\!\\ \\!\\ \\! ');

  
    output = output.replace(/lim\((.*?)(が|,)(.*?)へ?\)/g,'\\displaystyle\\lim_{$1 \\to $3} ');    
    output = output.replace(/(シグマ|しぐま|sum)\((.*?)(から|,)(.*?)\)/g,'\\displaystyle\\sum_{$2}^{$4} ');

    output = output.replace(/(任意の?|すてべの?)\((.*?)\)/g,'{}^{\\forall}{$2} ');
    output = output.replace(/ある\((.*?)\)/g,'{}^{\\exists}{$1} ');

    output = output.replace(/log\((.*?)\)/g,'\\log_{$1} ');

  
    output = output.replace(/<=>|&lt;=&gt;/g,'\\Longleftrightarrow ');
    output = output.replace(/<=|&lt;=/g,'\\Longleftarrow ');
    output = output.replace(/=>|=&gt;/g,'\\Longrightarrow ');
    output = output.replace(/=<|=&lt;/g,'\\le ');
    output = output.replace(/>=|&gt;=/g,'\\ge ');
    output = output.replace(/(ヘルプ|help)\(積分\)/g,'積分（１から４）\\Longrightarrow \\int_{1}^{4}, 積分（）\\Longrightarrow \\int ');
    output = output.replace(/(ヘルプ|help)\(順列\)/g,' \\_\\{n\\}P\\_\\{m\\}\\Longrightarrow \_\{n\}P\_\{m\}');
    output = output.replace(/(ヘルプ|help)\(組み合わせ\)/g,' \\_\\{n\\}C\\_\\{m\\}\\Longrightarrow \_\{n\}C\_\{m\}');
    output = output.replace(/(ヘルプ|help)\(数列\)/g,' x\\_n\\Longrightarrow x_n');
    
    var replacements = {  // 0:左側, 1:置換する語句, 2:右側
      '乗根(': ['\\sqrt[',{},'} '],
      'ルート(': ['\\sqrt{\\mathstrut ',{},'} '],
      'オーバー(': ['\\overline{ ',{},'} '],
      'アンダー(': ['\\underline{ ',{},'} '],
      'ベクトル(': ['\\overrightarrow{ ',{},'} '],
      'in(': ['\\in{ ',{},'} '],      
      'ni(': ['\\ni{ ',{},'} '],      
      'sub(': ['\\subseteq{ ',{},'} '],
      'bus(': ['\\supseteq{ ',{},'} '],
      '行列(': ['\\left(\\begin{array}{c}',{'\\),\\(':'\\\\',',':' & '},'\\end{array}\\right) '],
      '連立(': ['\\left\\{\\begin{array}{l}',{',':'\\\\ '},'\\end{array}\\right. '],
    }
    for (var word in replacements){
      var temp = replacements[word];
      while(output.indexOf(word)>=0){
        var start = output.indexOf(word);
        var count = 0;
        var len = word.length
        for (var end=start+len,J=output.length; end<J; end++){
          var character = output.charAt(end);
          if (character=='(') count++;
          else if (character==')') count--;
          if (count<0) break;
        }
        var inside = output.slice(start+len,end);
        if (word=='行列(') inside = inside.slice(1,inside.length-1);
        else if (word=='乗根('){
          if (start>0) start--;
          if (output.charAt(start)==')'){
            var middle = start;
            var count = 0;
            while (start>0 && count>=0){
              start--;
              if (output.charAt(start)==')') count++;
              else if (output.charAt(start)=='(') count--;
            }
            inside = output.slice(start+1,middle)+']{'+inside;
          }
          else inside = output.charAt(start)+']{'+inside;
        }
        for (var before in temp[1]) inside = inside.replace(new RegExp(before,'g'),temp[1][before]);
        output = output.slice(0,start)+temp[0]+inside+temp[2]+output.slice(end+1);
      }
    }

    output = output.replace(/(ヘルプ|help)\(集合\)/g,'in(X)\\Longrightarrow \\in X,ni(x)\\Longrightarrow \\ni,sub(X)\\Longrightarrow \\subseteq X,bus(X)\\Longrightarrow \\supseteq X');
    output = output.replace(/(ヘルプ|help)\(ルート\)/g,'ルート (x) \\Longrightarrow \\sqrt{x}\\\\ \\ n 乗根 (x) \\Longrightarrow \\sqrt[n]{x}\\\\ \\ (n+m) 乗根 (x) \\Longrightarrow \\sqrt[n+m]{x} ');


//    output = output.replace(/\(/g,'\\left(\\right. ');
//    output = output.replace(/\)/g,'\\left.\\right) ');

    var jpnCommand = { 'アルファ':'\\alpha ','α':'\\alpha ','ベータ':'\\beta ','β':'\\beta ','ガンマ':'\\gamma ','γ':'\\gamma ','プラスマイナス':'\\pm ','パイ|ぱい':'\\pi ','無限大':'\\infty ','・・・':'\\cdots ','プラマイ':'\\pm ','マイプラ':'\\mp ','not':'\\not ','➗|÷':'\\div ','×':'\\times ','≡':'\\equiv ','θ|シータ|Θ':'\\theta '};
    for (var myJpn in jpnCommand)
      output = output.replace(new RegExp(myJpn,'g'),jpnCommand[myJpn]);

   
    return output;
  }

  function PreView1(){
    var exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
    input = document.getElementById('response_content').value;
    if((input).match(exp)){
      document.getElementById('realtime').innerHTML = input;
    }else{
      document.getElementById('realtime').innerHTML = '$\\displaystyle{'+MathChange(input)+'}$';
      MathJax.Hub.Typeset();
    }
  }
    function PreView2(){
    var exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
    input = document.getElementById('article_content').value;
    if((input).match(exp)){
      document.getElementById('realtime').innerHTML = input;
    }else{
      document.getElementById('realtime').innerHTML = '$\\displaystyle{'+MathChange(input)+'}$';
      MathJax.Hub.Typeset();
    }
  }


  $(document).ready(function() {
      var exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
      for(var n=0,N=document.getElementsByTagName('div1').length; n<N; n++) {
      var tagname =document.getElementsByTagName('div1')[n].innerHTML;

        if((tagname).match(exp)){
          $(document.getElementsByTagName('div1')[n]).html($(document.getElementsByTagName('div1')[n]).html().replace(exp,"<a href='$1' target='_blank'>$1</a>"));
        }else{
          document.getElementsByTagName('div1')[n].innerHTML = '$\\displaystyle{'+MathChange(tagname)+'}$';
          MathJax.Hub.Typeset();
        };
      };
  });
    
  </script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', root_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.name %></td>
        <td><%= response.content %></td>
        <td><%= response.article_id %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response_path(response), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>
<%= link_to 'Top', root_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @response.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @response.content %>
</p>

<p>
  <strong>Article:</strong>
  <%= @response.article_id %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', root_path %>